"""Prometheus metrics for kunipy.

Mirrors the original C++ `kuni`'s `llm_usage_*` counters: input/output token
usage broken down by model, chat, and the code path that triggered the LLM
call (the "function" label). In the original, this breakdown is provided by
a `MetricsBreadcrumbs::Point` RAII helper that annotates the current
context; here we get the same effect with a plain `contextvars.ContextVar`
and a small context manager (`breadcrumbs`).

The metrics endpoint is exposed on port 9464 by default, matching the
original, and is independent of the (optional) OpenAI-compatible proxy
server -- it always starts alongside the app.
"""

from __future__ import annotations

import contextvars
import logging
from contextlib import contextmanager
from typing import Iterator, Optional

from prometheus_client import CollectorRegistry, Counter, generate_latest, CONTENT_TYPE_LATEST

logger = logging.getLogger(__name__)

REGISTRY = CollectorRegistry()

_LABELS = ("model", "chat", "function")

llm_usage_input = Counter(
    "llm_usage_input", "Total input (prompt) tokens sent to the LLM", _LABELS, registry=REGISTRY,
)
llm_usage_input_cache_hit = Counter(
    "llm_usage_input_cache_hit", "Input tokens served from the provider's prompt cache", _LABELS, registry=REGISTRY,
)
llm_usage_input_cache_miss = Counter(
    "llm_usage_input_cache_miss", "Input tokens that missed the provider's prompt cache", _LABELS, registry=REGISTRY,
)
llm_usage_output = Counter(
    "llm_usage_output", "Output (completion) tokens generated by the LLM", _LABELS, registry=REGISTRY,
)

_current_chat: contextvars.ContextVar[str] = contextvars.ContextVar("kunipy_metrics_chat", default="unknown")
_current_function: contextvars.ContextVar[str] = contextvars.ContextVar("kunipy_metrics_function", default="unknown")


@contextmanager
def breadcrumbs(chat: Optional[str] = None, function: Optional[str] = None) -> Iterator[None]:
    """Annotate the current async context with a chat/function label for the
    duration of the `with` block, so any `record_usage()` call made inside
    (even several layers down the call stack) picks it up automatically.

    Usage::

        with breadcrumbs(chat=f"chat_{chat_id}", function="worker.generate_response"):
            await openai.chat(...)
    """
    chat_token = _current_chat.set(chat) if chat is not None else None
    func_token = _current_function.set(function) if function is not None else None
    try:
        yield
    finally:
        if chat_token is not None:
            _current_chat.reset(chat_token)
        if func_token is not None:
            _current_function.reset(func_token)


def record_usage(
    model: str,
    prompt_tokens: int = 0,
    completion_tokens: int = 0,
    cached_tokens: int = 0,
) -> None:
    """Record token usage for one LLM call, labeled with the current breadcrumbs."""
    chat = _current_chat.get()
    function = _current_function.get()

    cache_hit = min(cached_tokens, prompt_tokens)
    cache_miss = max(prompt_tokens - cache_hit, 0)

    if cache_hit:
        llm_usage_input_cache_hit.labels(model=model, chat=chat, function=function).inc(cache_hit)
    if cache_miss:
        llm_usage_input_cache_miss.labels(model=model, chat=chat, function=function).inc(cache_miss)
    if prompt_tokens:
        llm_usage_input.labels(model=model, chat=chat, function=function).inc(prompt_tokens)
    if completion_tokens:
        llm_usage_output.labels(model=model, chat=chat, function=function).inc(completion_tokens)


def render_metrics() -> tuple[bytes, str]:
    """Return the current metrics in Prometheus text exposition format."""
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST


async def start_metrics_server(port: int = 9464) -> None:
    """Start a tiny standalone HTTP server exposing `/metrics` on `port`."""
    import uvicorn
    from fastapi import FastAPI
    from fastapi.responses import Response

    app = FastAPI(title="kunipy metrics")

    @app.get("/metrics")
    async def metrics() -> Response:
        body, content_type = render_metrics()
        return Response(content=body, media_type=content_type)

    config = uvicorn.Config(app, host="0.0.0.0", port=port, log_level="warning")
    server = uvicorn.Server(config)
    logger.info(f"Metrics server listening on http://0.0.0.0:{port}/metrics")
    await server.serve()
